### PR TITLE
revamped website

### PR DESCRIPTION
**Pull request by pjb7687**

### CODE REVIEW

**Comment by pjb7687** [comment]
I merged this since anything would be better than nothing... Thanks!

**Comment by slayoo** [comment]
Thanks! How to deploy it?
The website still shows this:
image

**Comment by pjb7687** [comment]
I thought `travis-sphinx deploy` does this automatically, but it doesn't seem to work.. I will try pushing to the `source` branch!

**Comment by pjb7687** [comment]
If it doesn't work, then I have no clues.. I only know how to deploy using Github actions.

**Comment by slayoo** [comment]
It does not work, I've reported it back in June 2019:
https://github.com/Syntaf/travis-sphinx/issues/47

**Comment by pjb7687** [comment]
I found the reason failed from Travis log. It is an authentication problem:

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gnudatalanguage/gnudatalanguage.github.io.git/'
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/ghp-import", line 8, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/ghp_import.py", line 275, in main
    ghp_import(args[0], **opts.__dict__)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/ghp_import.py", line 259, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'], '--force')
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/opt/python/3.6.7/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'https://[secure]@github.com/gnudatalanguage/gnudatalanguage.github.io.git', 'gh-pages', '--force']' returned non-zero exit status 128.
Error: /home/travis/virtualenv/python3.6.7/bin/ghp-import -p -f -n -r https://[secure]@github.com/gnudatalanguage/gnudatalanguage.github.io.git -m Update\ documentation doc/build
Done. Your build exited with 0.
```

**Comment by pjb7687** [comment]
Seems like you can fix it by adding your personal access token to Travis build environment variable. However, I think GA is better in terms of security since it doesn't require access tokens stored as environment variables. What do you think?

**Comment by slayoo** [comment]
Jeongbin, if only you could make it work with GA, I'm of course totally fine to switch to it

**Comment by pjb7687** [comment]
That is super easy... Wait a moment

**Comment by pjb7687** [comment]
Done. Any pushes to the `source` branch will deploy website.

**Comment by pjb7687** [comment]
Well I can't delete `master` branch, but you can change default branch to `source` and remove `master`.

**Comment by slayoo** [comment]
done!
big big thanks!

**Pull request merged**
